spring:
  application:
    name: boot
  http:
    encoding:
      force: true
      force-response: true
    converters:
      preferred-json-mapper: jackson
  aop:
    proxy-target-class: true
    auto: true
  redis:
    host: localhost
    port: 6379
    password: redis#root
    timeout: 2000s
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000s
    database: 0
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 6000s
      use-key-prefix: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      scheduler:
        instanceName: simpleScheduler
        instanceId: AUTO
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 25
        threadPriority: 5
      jobStore:
        misfireThreshold: 60000
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        useProperties: false
        dataSource: mysql
        tablePrefix: QRTZ_
        isClustered: true
        clusterCheckinInterval: 20000
      dataSource:
        mysql:
          driver: com.mysql.cj.jdbc.Driver
          URL: jdbc:mysql://:3306/quartz?characterEncoding=UTF8&serverTimezone=GMT&useUnicode=true&autoReconnect=true&useSSL=false
          user: mysql
          password: mysql#root
          maxConnections: 5
          validationQuery: select 0
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      generate-unique-name: true
      sql-script-encoding: UTF-8
      username: mysql
      password: mysql#root
      url: jdbc:mysql://:3306/mydb?characterEncoding=UTF8&serverTimezone=GMT&useUnicode=true&autoReconnect=true&useSSL=false
      type: com.zaxxer.hikari.HikariDataSource
  slave:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      generate-unique-name: true
      sql-script-encoding: UTF-8
      username: mysql
      password: mysql#root
      url: jdbc:mysql://:3306/awesome?characterEncoding=UTF8&serverTimezone=GMT&useUnicode=true&autoReconnect=true&useSSL=false
      type: com.zaxxer.hikari.HikariDataSource
server:
  http2:
    enabled: true
  port: 7070
  undertow:
    accesslog:
      enabled: true
      dir: logger
      prefix: req_log.
debug: true
mybatis:
  check-config-location: true
  type-aliases-package: com.api.boot.modules.domain
  mapper-locations: classpath:/com/api/boot/modules/mapper/*.xml
  configuration:
    aggressive-lazy-loading: true
    cache-enabled: true
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level: debug
  file: sys_log
