spring:
  application:
    name: boot
  http:
    encoding:
      force: true
      force-response: true
    converters:
      preferred-json-mapper: jackson
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql#root
    url: jdbc:mysql://:3306/mydb?characterEncoding=UTF8&serverTimezone=GMT&useUnicode=true&autoReconnect=true&useSSL=false
    name: Hikari
    hikari:
      read-only: false
      auto-commit: true
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      data-source-properties:
        cachePrepStmts: false
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      max-lifetime: 18000
  aop:
    proxy-target-class: true
    auto: true
  redis:
    host: localhost
    port: 6379
    password: gentoo
    timeout: 2000s
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000s
    database: 0
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 6000s
      use-key-prefix: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      scheduler:
        instanceName: simpleScheduler
        instanceId: AUTO
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 25
        threadPriority: 5
      jobStore:
        misfireThreshold: 60000
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        useProperties: false
        dataSource: mysql
        tablePrefix: QRTZ_
        isClustered: true
        clusterCheckinInterval: 20000
      dataSource:
        mysql:
          driver: com.mysql.cj.jdbc.Driver
          URL: jdbc:mysql://:3306/quartz?characterEncoding=UTF8&serverTimezone=GMT&useUnicode=true&autoReconnect=true&useSSL=false
          user: mysql
          password: mysql#root
          maxConnections: 5
          validationQuery: select 0
server:
  http2:
    enabled: true
  port: 7070
  undertow:
    accesslog:
      enabled: true
debug: true
mybatis:
  check-config-location: true
  type-aliases-package: com.api.boot.modules.domain
  mapper-locations: classpath:/com/api/boot/modules/mapper/*.xml
  configuration:
    aggressive-lazy-loading: true
    cache-enabled: true
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level: debug
